services:
  db:
    image: mysql:8.0
    container_name: halloween_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: halloween_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: halloween_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=halloween_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=halloween_db
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: halloween_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
